local_costmap:
  global_frame: $(arg prefix)odom
  robot_base_frame: $(arg prefix)base_footprint
  update_frequency: 10.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 3
  height: 3
  resolution: 0.05
  transform_tolerance: 2.0
  
  plugins:
   - {name: static_layer,        type: "costmap_2d::StaticLayer"}
   - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}
  