NavfnROS:
  allow_unknown: true # Specifies whether or not to allow navfn to create plans that traverse unknown space.
  default_tolerance: 0.1 # A tolerance on the goal point for the planner.

  cost_factor: 0.55
  neutral_cost: 66
  lethal_cost: 253

